apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-test
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-test
        image: jaadds/azure_test:master-2de847a436395e2ba59c36d13ef0ac404b376eaa
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "azure-test"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080  
  selector:
    app: azure-test
